import { lenders, Lender } from '@/Data/lenders';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { Download, X, TrendingUp, Percent, Calendar, Award, Clock, CreditCard, AlertCircle, Check, CheckCircle, Loader2 } from 'lucide-react';
import React, { useRef, useState } from 'react';

import { domToPng } from 'modern-screenshot';
import jsPDF from 'jspdf';

interface ProvisionalOfferLetterProps {
  onClose: () => void;
  onApplyNow: (lender: Lender) => void;
}

export const ProvisionalOfferLetter = ({ onClose, onApplyNow }: ProvisionalOfferLetterProps) => {
  const contentRef = useRef<HTMLDivElement>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  const today = new Date();
  const formattedDate = today.toLocaleDateString('en-IN', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });

  const referenceId = `HPR/POL/${today.getFullYear().toString().slice(-2)}${(today.getMonth() + 1).toString().padStart(2, '0')}${today.getDate().toString().padStart(2, '0')}/${Math.floor(1000 + Math.random() * 9000)}`;

  // Sort lenders by approval probability (highest first)
  const rankedLenders = [...lenders].sort((a, b) => b.approvalProbability - a.approvalProbability);

  const getApprovalColor = (probability: number) => {
    if (probability >= 90) return 'text-green-600';
    if (probability >= 80) return 'text-blue-600';
    return 'text-orange-500';
  };

  const handleDownloadPDF = async () => {
    if (!contentRef.current) return;
    
    setIsDownloading(true);
    
    try {
      // Hide buttons temporarily
      const downloadBtn = document.querySelector('.download-btn') as HTMLElement;
      const closeBtn = document.querySelector('.close-btn') as HTMLElement;
      const closeBtnBottom = document.querySelector('.close-btn-bottom') as HTMLElement;
      
      if (downloadBtn) downloadBtn.style.display = 'none';
      if (closeBtn) closeBtn.style.display = 'none';
      if (closeBtnBottom) closeBtnBottom.style.display = 'none';

      // Use modern-screenshot which handles oklch colors properly
      const dataUrl = await domToPng(contentRef.current, {
        scale: 2,
        backgroundColor: '#ffffff',
      });

      // Restore buttons
      if (downloadBtn) downloadBtn.style.display = '';
      if (closeBtn) closeBtn.style.display = '';
      if (closeBtnBottom) closeBtnBottom.style.display = '';

      // Create image to get dimensions
      const img = new Image();
      img.src = dataUrl;
      
      await new Promise((resolve) => {
        img.onload = resolve;
      });

      // Calculate PDF dimensions
      const imgWidth = 210; // A4 width in mm
      const imgHeight = (img.height * imgWidth) / img.width;
      
      // Create PDF
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      // Add image to PDF
      let heightLeft = imgHeight;
      let position = 0;
      
      pdf.addImage(dataUrl, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= 297; // A4 height in mm
      
      // Add new pages if content is longer than one page
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(dataUrl, 'PNG', 0, position, imgWidth, imgHeight);
        heightLeft -= 297;
      }
      
      // Save the PDF
      pdf.save(`Provisional_Offer_Letter_${referenceId.replace(/\//g, '_')}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  };


  return (
    <div className="max-w-6xl mx-auto px-6">
    {isDownloading && (
        <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center">
          <div className="bg-white rounded-2xl px-8 py-6 flex items-center gap-3 shadow-xl">
            <Loader2 className="w-6 h-6 animate-spin text-blue-600" />
            <span className="font-medium text-gray-700">
              Generating PDF, please wait...
            </span>
          </div>
        </div>
      )}
    <div className="animate-fade-in" ref={contentRef}>
      {/* Header */}
      <div className="flex items-start justify-between mb-4">
        <div>
          <h5 className="text-2xl !font-bold italic text-gray-950 mb-0.5">
            PROVISIONAL OFFER LETTER
          </h5>

          <p className="text-md text-gray-500 mt-1">
            Generated by Happirate AI Smart Lending Engine
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button 
            onClick={handleDownloadPDF}
            disabled={isDownloading}
            className="gradient-primary hover:opacity-90 !rounded-xl download-btn" 
            size="sm"
          >
            {isDownloading ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Downloading...
              </>
            ) : (
              <>
                <Download className="w-3 h-3.5 mr-1.5" />
                Download All
              </>
            )}
          </Button>

          <button
            onClick={onClose}
            className="p-1.5 hover:bg-secondary rounded-lg transition-colors close-btn"
          >
            <X className="w-4 h-4 text-muted-foreground" />
          </button>
        </div>
      </div>

      <div className="border-t border-border pt-6">
        {/* Application Snapshot */}
        <div className="card-elevated p-2.5 mb-6">
          <h2 className="!text-[#3B82F6] !text-xl !font-bold italic mb-4 pt-2">
            Application Snapshot
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 text-sm mb-4">
            <div className="flex flex-col">
              <span className="text-muted-foreground text-xs mb-1">Date</span>
              <span className="font-semibold">{formattedDate}</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground text-xs mb-1">Ref ID</span>
              <span className="font-semibold text-navy truncate">{referenceId}</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground text-xs mb-1">Borrower</span>
              <span className="font-semibold">Maya Reddy</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground text-xs mb-1">Loan Type</span>
              <span className="font-semibold">Personal</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground text-xs mb-1">CIBIL</span>
              <span className="font-semibold text-green-600">785</span>
            </div>
            <div className="flex flex-col">
              <span className="text-muted-foreground text-xs mb-1">Requested</span>
              <span className="font-semibold">₹12,345 / 5Y</span>
            </div>
          </div>
        </div>

        {/* Eligible Offers */}
        <div className="mb-6">
          <h2 className="font-display !text-xl !font-bold text-gray-950 mb-2">
            ELIGIBLE OFFERS ({rankedLenders.length})
          </h2>
          <p className="text-muted-foreground text-sm mb-4">
            Ranked by approval probability based on your profile
          </p>

          <div className="space-y-4">
            {rankedLenders.map((lender, index) => (
              <div
                key={lender.id}
                className={cn(
                  'card-elevated px-5 py-4 transition-all relative',
                  index === 0 && 'border-2 border-green-500 hover:border-gray-200'
                )}
              >
              {index === 0 && (
                <div className="absolute -top-3 left-4 inline-flex items-center gap-1.5 bg-green-500 text-white px-3 py-1 rounded-full text-xs font-semibold shadow">
                  <Award className="w-3 h-3" />
                  Best Match
                </div>
              )}
                <div className="flex flex-col lg:flex-row items-start gap-4">
                  {/* Lender Info */}
                  <div className="flex items-center gap-3 lg:w-48 flex-shrink-0">
                    <div
                      className={cn(
                        'w-12 h-12 rounded-2xl flex items-center justify-center font-bold text-sm text-white',
                        lender.type === 'Bank' ? 'bg-slate-900' : 'bg-blue-500'
                      )}
                    >
                      {lender.logo.slice(0, 3)}
                    </div>
                    <div className="min-w-0">
                      <div className="text-xs text-muted-foreground">#{index + 1}</div>
                      <h6 className="font-display !font-bold text-gray truncate">{lender.name}</h6>
                      <span className={cn(
                        'text-xs px-2 py-0.5 rounded',
                        lender.type === 'Bank' ? 'bg-gray-300 text-gray-600' : ' bg-blue-100 text-blue-600'
                      )}>
                        {lender.type}
                      </span>
                    </div>
                  </div>

                  {/* Key Metrics */}
                  <div className="flex-1 grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-6 text-sm">
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs flex items-center gap-1 mb-1">
                        <CreditCard className="w-3 h-3" /> Sanction
                      </span>
                      <span className="font-bold">Up to ₹{(lender.maxSanctionAmount / 100000).toFixed(0)}L</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs flex items-center gap-1 mb-1">
                        <Percent className="w-3 h-3" /> APR
                      </span>
                      <span className="font-bold">{lender.trueAPR}–{lender.trueAPRMax}%</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs flex items-center gap-1 mb-1">
                        <Calendar className="w-3 h-3" /> Tenure
                      </span>
                      <span className="font-bold">{lender.tenureOptions}</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs flex items-center gap-1 mb-1">
                        <AlertCircle className="w-3 h-3" /> Proc. Fee
                      </span>
                      <span className="font-bold">{lender.processingFeeMin}–{lender.processingFeeMax}%</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs flex items-center gap-1 mb-1">
                        <TrendingUp className="w-3 h-3" /> Approval
                      </span>
                      <span className={cn('font-bold text-green-600', getApprovalColor(lender.approvalProbability))}>
                        {lender.approvalProbability}%
                      </span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs flex items-center gap-1 mb-1">
                        <Clock className="w-3 h-3" /> Disbursal
                      </span>
                      <span className="font-bold">{lender.disbursalTime}</span>
                    </div>
                    <div className="flex flex-col">
                      <span className="text-muted-foreground text-xs mb-1">Prepay</span>
                      <span className="font-medium text-xs">{lender.prepaymentCharges}</span>
                    </div>
                  </div>

                  {/* Apply Button */}
                  <div className="flex items-center lg:w-28 flex-shrink-0">
                    <Button
                      onClick={() => onApplyNow(lender)}
                      className="gradient-primary text-white !rounded-xl px-6 py-2 shadow"
                      size="default"
                    >
                      Apply Now
                    </Button>
                  </div>
                </div>

                {/* Pros, Cons, Advantages */}
                <div className="mt-4 pt-2 border-t border-border grid grid-cols-1 md:grid-cols-3 gap-4 text-sm">
                  <div>
                    <span className="font-semibold text-green-600 flex items-center gap-1 mb-2">
                      <CheckCircle className="w-4 h-4 text-green-600" /> Pros
                    </span>
                    <ul className="text-muted-foreground space-y-1.5">
                      {lender.pros.slice(0, 2).map((pro, i) => (
                        <li key={i} className="flex items-start gap-1.5 leading-snug">
                          <Check className="w-3.5 h-3.5 text-green-600 flex-shrink-0 mt-0.5" />
                          <span>{pro}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <span className="font-semibold text-warning flex items-center gap-1 mb-2">
                      <AlertCircle className="w-4 h-4" /> Cons
                    </span>
                    <ul className="text-muted-foreground space-y-1.5">
                      {lender.cons.slice(0, 2).map((con, i) => (
                        <li key={i} className="flex items-start gap-1.5 leading-snug">
                          <X className="w-3.5 h-3.5 text-warning flex-shrink-0 mt-0.5" />
                          <span>{con}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <span className="font-semibold text-trust flex items-center gap-1 mb-2">
                      <Award className="w-4 h-4 text-blue-600" /> Unique
                    </span>
                    <ul className="text-muted-foreground space-y-1.5">
                      {lender.uniqueAdvantages.slice(0, 2).map((adv, i) => (
                        <li key={i} className="flex items-start gap-1.5 leading-snug">
                          <Award className="w-3.5 h-3.5 text-trust flex-shrink-0 mt-0.5 text-blue-600" />
                          <span>{adv}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Close Button */}
        <div className="text-center py-4 border-t border-border close-btn-bottom">
        <Button
          variant="ghost"
          onClick={onClose}
          className="
            !rounded-xl
            text-gray-500
            transition-all
            hover:bg-purple-600
            hover:text-white
            hover:shadow-md
          "
        >
          Close Letter
        </Button>
        </div>
      </div>
    </div>
    </div>
  );
};
